name: '.NET-DTDL Parser-Pack and push'

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore sources/IoT.Simulator/IoT.DTDL/IoT.DTDL.csproj
    - name: Build
      run: dotnet build --no-restore sources/IoT.Simulator/IoT.DTDL/IoT.DTDL.csproj
    - name: Pack
      run: dotnet pack --configuration Release sources/IoT.Simulator/IoT.DTDL/IoT.DTDL.csproj
    - name: Push
      env:
        PACKAGE_PAT=${{ secrets.SuperSecret }}
      run: dotnet nuget push "bin/Release/*.nupkg"  --api-key $PACKAGE_PAT --source "github" sources/IoT.Simulator/IoT.DTDL/IoT.DTDL.csproj
